# Generated by Django 2.2.6 on 2019-11-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=200)),
                ('site_id', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('census', models.CharField(max_length=200)),
                ('habitation', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work.Site')),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
            ],
            bases=('work.site',),
        ),
        migrations.CreateModel(
            name='SurveyQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht', models.FloatField()),
                ('pole_ht', models.IntegerField()),
                ('lt3', models.FloatField()),
                ('lt1', models.FloatField()),
                ('pole_lt', models.IntegerField()),
                ('approval_status', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Site')),
            ],
        ),
    ]
