# Generated by Django 2.2.6 on 2019-11-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyqty',
            name='pole_ht',
        ),
        migrations.RemoveField(
            model_name='surveyqty',
            name='pole_lt',
        ),
        migrations.AddField(
            model_name='surveyqty',
            name='dtr_100',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyqty',
            name='dtr_25',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyqty',
            name='dtr_63',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyqty',
            name='pole_8m',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyqty',
            name='pole_9m',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
