# Generated by Django 2.2.6 on 2019-11-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht', models.FloatField()),
                ('lt_3p', models.FloatField()),
                ('lt_1p', models.FloatField()),
                ('pole_lt_8m', models.IntegerField()),
                ('pole_ht_8m', models.IntegerField()),
                ('dtr_100', models.IntegerField()),
                ('dtr_63', models.IntegerField()),
                ('dtr_25', models.IntegerField()),
                ('remark', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Site')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftedQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acsr', models.FloatField()),
                ('cable_3p', models.FloatField()),
                ('cable_1p', models.FloatField()),
                ('pole_8m', models.IntegerField()),
                ('pole_9m', models.IntegerField()),
                ('dtr_100', models.IntegerField()),
                ('dtr_63', models.IntegerField()),
                ('dtr_25', models.IntegerField()),
                ('remark', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Site')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
