# Generated by Django 2.2.6 on 2019-11-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20191102_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressqty',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.Site'),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.Site'),
        ),
    ]
