# Generated by Django 2.2.6 on 2019-11-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20191102_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressqty',
            name='dtr_100',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='dtr_25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='dtr_63',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='ht',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='lt_1p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='lt_3p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='pole_ht_8m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='pole_lt_8m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='acsr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='cable_1p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='cable_3p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='dtr_100',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='dtr_25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='dtr_63',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='pole_8m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='pole_9m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='approval_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='dtr_100',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='dtr_25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='dtr_63',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='ht',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='lt1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='lt3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='pole_8m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='pole_9m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
