# Generated by Django 2.2.6 on 2019-11-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20191103_0727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('village', 'census', 'habitation')},
        ),
    ]
