# Generated by Django 2.2.6 on 2019-11-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20191103_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('approve_id', 'village', 'census', 'habitation')},
        ),
    ]
