# Generated by Django 2.2.6 on 2019-11-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_progressqtyextra_shiftedqtyextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftedqtyextra',
            name='site',
        ),
    ]
