# Generated by Django 2.2.6 on 2019-11-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_remove_shiftedqtyextra_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hab_id', models.CharField(max_length=200, unique=True)),
                ('approve_id', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('census', models.CharField(max_length=200)),
                ('habitation', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='progressqtyextra',
            name='hab_id',
        ),
        migrations.RemoveField(
            model_name='shiftedqtyextra',
            name='hab_id',
        ),
        migrations.AddField(
            model_name='progressqtyextra',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.SiteExtra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftedqtyextra',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.SiteExtra'),
            preserve_default=False,
        ),
    ]
