# Generated by Django 2.2.6 on 2019-11-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20191105_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyqty',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.Site'),
        ),
    ]
