# Generated by Django 2.2.6 on 2019-11-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_auto_20191105_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='DprInfra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lt_material', models.CharField(blank=True, max_length=200, null=True)),
                ('lt_length', models.FloatField(blank=True, null=True)),
                ('ht_material', models.CharField(blank=True, max_length=200, null=True)),
                ('ht_length', models.FloatField(blank=True, null=True)),
                ('dtr_material', models.CharField(blank=True, max_length=200, null=True)),
                ('dtr_no', models.IntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Site')),
            ],
        ),
        migrations.CreateModel(
            name='DprHH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('hh_bpl', models.IntegerField(blank=True, null=True)),
                ('hh_bpl_metered', models.IntegerField(blank=True, null=True)),
                ('hh_metered', models.IntegerField(blank=True, null=True)),
                ('hh_unmetered', models.IntegerField(blank=True, null=True)),
                ('apl_free', models.IntegerField(blank=True, null=True)),
                ('apl_not_free', models.IntegerField(blank=True, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.Site')),
            ],
        ),
    ]
