# Generated by Django 2.2.6 on 2019-11-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_dprhh_dprinfra'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='block',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
