# Generated by Django 2.2.6 on 2019-11-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_site_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dprhh',
            old_name='apl_free',
            new_name='hh_apl_free',
        ),
        migrations.RemoveField(
            model_name='dprhh',
            name='apl_not_free',
        ),
        migrations.AddField(
            model_name='dprhh',
            name='hh_apl_not_free',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
