# Generated by Django 2.2.6 on 2019-11-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_auto_20191105_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprhh',
            name='remark',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
