# Generated by Django 2.2.6 on 2019-11-06 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_auto_20191106_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprinfra',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.Site'),
        ),
    ]
