# Generated by Django 2.2.6 on 2019-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0028_auto_20191106_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprqty',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressqtyextra',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqty',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedqtyextra',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteextra',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
