# Generated by Django 2.2.6 on 2019-11-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0030_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
