# Generated by Django 2.2.6 on 2019-11-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0031_auto_20191107_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteextra',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.Site'),
        ),
    ]
