# Generated by Django 2.2.6 on 2019-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_siteextra_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='census',
            field=models.IntegerField(),
        ),
    ]
