# Generated by Django 2.2.6 on 2019-11-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0033_auto_20191108_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteextra',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Site'),
        ),
    ]
