# Generated by Django 2.2.6 on 2019-11-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0034_auto_20191108_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='approve_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteextra',
            name='approve_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
