# Generated by Django 2.2.6 on 2019-11-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0035_auto_20191112_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprqty',
            name='has_infra',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
