# Generated by Django 2.2.6 on 2019-11-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0037_auto_20191114_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('resolution', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('done', 'done'), ('pending', 'pending')], max_length=10, null=True)),
            ],
        ),
    ]
