# Generated by Django 2.2.6 on 2019-11-25 08:10

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0038_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='document',
            field=models.FileField(null=True, upload_to=work.models.HeadlineDocPath),
        ),
        migrations.AddField(
            model_name='headline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
