# Generated by Django 2.2.6 on 2019-11-25 08:13

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0040_remove_headline_changeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=work.models.HeadlineDocPath),
        ),
    ]
