# Generated by Django 2.2.6 on 2019-11-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0041_auto_20191125_0813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headline',
            new_name='Resolution',
        ),
    ]
