# Generated by Django 2.2.6 on 2019-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0042_auto_20191125_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='census',
            field=models.IntegerField(default=0),
        ),
    ]
