# Generated by Django 2.2.6 on 2019-11-30 07:28

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0045_auto_20191129_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressqty',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=work.models.habCompletionDocPath),
        ),
        migrations.AlterField(
            model_name='progressqtyextra',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=work.models.habCompletionDocPath),
        ),
    ]
