# Generated by Django 2.2.6 on 2019-11-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0046_auto_20191130_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.Site'),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='completed or others'),
        ),
    ]
