# Generated by Django 2.2.6 on 2019-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0047_auto_20191130_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressqty',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('not started', 'not started'), ('canceled', 'canceled')], max_length=200, null=True, verbose_name='completed or others'),
        ),
        migrations.AlterField(
            model_name='progressqtyextra',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('not started', 'not started'), ('canceled', 'canceled')], max_length=100, null=True),
        ),
    ]
