# Generated by Django 2.2.6 on 2019-11-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0048_auto_20191130_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
