# Generated by Django 2.2.6 on 2019-12-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0050_auto_20191130_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressqty',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('not started', 'not started'), ('canceled', 'canceled')], max_length=200, null=True),
        ),
    ]
