# Generated by Django 2.2.6 on 2019-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0053_auto_20191203_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteextra',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
