# Generated by Django 2.2.6 on 2019-12-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0055_auto_20191205_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressqty',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='progressqtyextra',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue')], max_length=50, null=True),
        ),
    ]
