# Generated by Django 2.2.6 on 2019-12-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0056_auto_20191205_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyqty',
            old_name='lt1',
            new_name='lt_1p',
        ),
        migrations.RenameField(
            model_name='surveyqty',
            old_name='lt3',
            new_name='lt_3p',
        ),
    ]
