# Generated by Django 2.2.6 on 2019-12-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0057_auto_20191205_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressqty',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('not reviewed', 'not review')], default='not reviewed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressqtyextra',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('not reviewed', 'not review')], default='not reviewed', max_length=50, null=True),
        ),
    ]
