# Generated by Django 2.2.6 on 2019-12-07 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('work', '0058_auto_20191206_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Resolution')),
            ],
        ),
    ]
