# Generated by Django 2.2.6 on 2019-12-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0061_historicaldprqty_historicallog_historicalprogressqty_historicalprogressqtyextra_historicalshiftedqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsurveyqty',
            name='pole_lt_8m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyqty',
            name='pole_lt_8m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
