# Generated by Django 2.2.6 on 2019-12-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0062_auto_20191207_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsurveyqty',
            name='pole_ht_8m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyqty',
            name='pole_ht_8m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
