# Generated by Django 2.2.6 on 2019-12-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0063_auto_20191207_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsurveyqty',
            name='pole_8m',
        ),
        migrations.RemoveField(
            model_name='surveyqty',
            name='pole_8m',
        ),
    ]
