# Generated by Django 2.2.6 on 2019-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0064_auto_20191207_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogressqty',
            name='pole_9m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogressqtyextra',
            name='pole_9m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressqty',
            name='pole_9m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressqtyextra',
            name='pole_9m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
