# Generated by Django 2.2.6 on 2019-12-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0066_historicalresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogressqty',
            name='cert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalprogressqtyextra',
            name='cert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressqty',
            name='cert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressqtyextra',
            name='cert',
            field=models.BooleanField(default=False),
        ),
    ]
