# Generated by Django 2.2.6 on 2019-12-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0067_auto_20191211_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresolution',
            name='status',
            field=models.CharField(blank=True, choices=[('done', 'done'), ('pending', 'pending'), ('deferred', 'deferred')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='status',
            field=models.CharField(blank=True, choices=[('done', 'done'), ('pending', 'pending'), ('deferred', 'deferred')], max_length=10, null=True),
        ),
    ]
