# Generated by Django 2.2.6 on 2019-12-13 14:09

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0069_auto_20191213_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht', models.FloatField(blank=True, null=True)),
                ('ht_conductor', models.FloatField(blank=True, null=True)),
                ('lt_1p', models.FloatField(blank=True, null=True)),
                ('lt_3p', models.FloatField(blank=True, null=True)),
                ('dtr_25', models.IntegerField(blank=True, null=True)),
                ('dtr_63', models.IntegerField(blank=True, null=True)),
                ('dtr_100', models.IntegerField(blank=True, null=True)),
                ('pole_lt_8m', models.IntegerField(blank=True, null=True)),
                ('pole_ht_8m', models.IntegerField(blank=True, null=True)),
                ('pole_9m', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(max_length=50, unique=True)),
                ('supply_cost', models.FloatField(blank=True, null=True)),
                ('erection_cost', models.FloatField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=work.models.LoaDocPath)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dprqty',
            name='ht_conductor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldprqty',
            name='ht_conductor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogressqty',
            name='ht_conductor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprogressqtyextra',
            name='ht_conductor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsurveyqty',
            name='ht_conductor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressqty',
            name='ht_conductor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressqtyextra',
            name='ht_conductor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyqty',
            name='ht_conductor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
