# Generated by Django 2.2.6 on 2019-12-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0072_habitationvariations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprqty',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dprqty',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dprqty',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dprqty',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldprqty',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldprqty',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldprqty',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldprqty',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogressqty',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('not reviewed', 'not reviewed')], default='not reviewed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogressqtyextra',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('not reviewed', 'not reviewed')], default='not reviewed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('not reviewed', 'not reviewed')], default='not reviewed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressqtyextra',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('not reviewed', 'not reviewed')], default='not reviewed', max_length=50, null=True),
        ),
    ]
