# Generated by Django 2.2.6 on 2019-12-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0075_auto_20191230_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveyqty',
            name='approval_status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='surveyqty',
            name='approval_status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
