# Generated by Django 2.2.6 on 2020-01-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0076_auto_20191231_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='remark',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalsiteextra',
            name='remark',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='remark',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteextra',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
