# Generated by Django 2.2.6 on 2020-01-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0077_auto_20200103_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsite',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalsiteextra',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteextra',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
