# Generated by Django 2.2.6 on 2020-01-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0078_auto_20200103_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogressqty',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('freeze', 'freeze'), ('not reviewed', 'not reviewed')], default='not reviewed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogressqtyextra',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('freeze', 'freeze'), ('not reviewed', 'not reviewed')], default='not reviewed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('freeze', 'freeze'), ('not reviewed', 'not reviewed')], default='not reviewed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressqtyextra',
            name='review',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('issue', 'issue'), ('freeze', 'freeze'), ('not reviewed', 'not reviewed')], default='not reviewed', max_length=50, null=True),
        ),
    ]
