# Generated by Django 2.2.6 on 2020-01-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0080_auto_20200110_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsite',
            name='hab_id',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsiteextra',
            name='hab_id',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='hab_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='siteextra',
            name='hab_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
