# Generated by Django 2.2.6 on 2020-01-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0081_auto_20200110_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsite',
            name='hab_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsiteextra',
            name='hab_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='hab_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='siteextra',
            name='hab_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
