# Generated by Django 2.2.6 on 2020-01-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0082_auto_20200110_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogressqty',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('not started', 'not started'), ('canceled', 'canceled')], default='not started', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalprogressqtyextra',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('not started', 'not started'), ('canceled', 'canceled')], default='not started', max_length=200),
        ),
        migrations.AlterField(
            model_name='progressqty',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('not started', 'not started'), ('canceled', 'canceled')], default='not started', max_length=200),
        ),
        migrations.AlterField(
            model_name='progressqtyextra',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('not started', 'not started'), ('canceled', 'canceled')], default='not started', max_length=200),
        ),
    ]
