# Generated by Django 2.2.6 on 2020-01-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0084_auto_20200110_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsurveyqty',
            old_name='approval_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='surveyqty',
            old_name='approval_status',
            new_name='status',
        ),
    ]
