# Generated by Django 2.2.6 on 2020-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0085_auto_20200112_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprqty',
            name='project',
            field=models.CharField(default='main', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaldprqty',
            name='project',
            field=models.CharField(default='main', max_length=10),
        ),
    ]
