# Generated by Django 2.2.6 on 2020-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0086_auto_20200117_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
    ]
