# Generated by Django 2.2.6 on 2020-01-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0088_auto_20200121_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
