# Generated by Django 2.2.6 on 2019-11-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0038_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('consumer_no', models.CharField(blank=True, max_length=50, null=True)),
                ('edate', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=50, null=True)),
                ('meter_no', models.CharField(blank=True, max_length=50, null=True)),
                ('apl_bpl', models.CharField(blank=True, max_length=3, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('voter_no', models.CharField(blank=True, max_length=20, null=True)),
                ('tariff', models.CharField(blank=True, max_length=20, null=True)),
                ('pdc_date', models.CharField(blank=True, max_length=20, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Site')),
            ],
        ),
    ]
