# Generated by Django 2.2.6 on 2019-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_auto_20191122_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='changeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
