# Generated by Django 2.2.6 on 2019-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_auto_20191123_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='isInPortal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
