# Generated by Django 2.2.6 on 2019-11-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0005_consumer_isinportal'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
