# Generated by Django 2.2.6 on 2020-01-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0009_consumer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='habitation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
